name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Si aggiorna ogni ora
  workflow_dispatch: # Ti permette di avviarlo manualmente per testare
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FraLiturri # <--- CAMBIA CON IL TUO USERNAME
          template: classic
          plugin_languages: yes
          plugin_languages_ignored: html, css # Escludi linguaggi meno rilevanti
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8 # Numero massimo di linguaggi da mostrare
          base: header, community, repositories, metadata
          config_timezone: Europe/Rome
          # Grafico isometrico dei contributi (3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Mostra gli ultimi 6 mesi
          filename: github-metrics.svg # Nome del file salvato nel repo
