name: Metrics
on:
  # Pianificazione: ogni ora
  schedule: [{cron: "0 * * * *"}]
  # Permette l'avvio manuale dalla scheda Actions
  workflow_dispatch:
  # Avvio automatico quando modifichi il file
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal Metrics
        uses: lowlighter/metrics@latest
        with:
          # Il token salvato nei Secrets del repository
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurazione Utente
          user: FraLiturri
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Rome
          
          # Output: salvataggio file locale nel repository
          filename: github-metrics.svg

          # PLUGIN: GRAFICO ISOMETRICO (3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # PLUGIN: LINGUAGGI
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          # ESCLUSIONE REPO: inserisci qui i nomi separati da virgola
          plugin_languages_skipped: francescoliturrri
          plugin_languages_limit: 8
          
          # OPZIONI AGGIUNTIVE
          config_padding: 0, 5%
          plugin_languages_threshold: 0% # Mostra anche linguaggi con bassa %
