name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Si aggiorna ogni ora
  workflow_dispatch: # Ti permette di avviarlo manualmente per testare
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tuo-username # <--- CAMBIA CON IL TUO USERNAME
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Rome
          filename: github-metrics.svg # Nome del file salvato nel repo
